#!/bin/bash -e


####
rm -rf ~/opt/GravitySpy-py27
virtualenv-2.7 ~/opt/GravitySpy-py27
. ~/opt/GravitySpy-py27/bin/activate
python -m pip install --upgrade --quiet pip setuptools
pip install .

rm -rf ~/opt/GravitySpy-py34
virtualenv-3.4 ~/opt/GravitySpy-py34
. ~/opt/GravitySpy-py34/bin/activate
python -m pip install --upgrade --quiet pip
pip install .

rm -rf ~/opt/GravitySpy-py36
source /opt/rh/rh-python36/enable
virtualenv ~/opt/GravitySpy-py36
. ~/opt/GravitySpy-py36/bin/activate
python -m pip install --upgrade --quiet pip
pip install .
