#!/bin/bash -e


####

mkdir -p ./build/py27/
cd ./build/py27/

export PATH=$PATH:/usr/local/cuda-9.2/bin/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64/

rm -rf ~/opt/GravitySpy-py27
virtualenv-2.7 ~/opt/GravitySpy-py27
. ~/opt/GravitySpy-py27/bin/activate
python -m pip install --upgrade --quiet pip setuptools
pip install ../../.
pip install lalsuite

git clone https://github.com/Theano/libgpuarray.git
cd libgpuarray

pip install cython
rm -rf build Build
mkdir Build
cd Build
cmake3 .. -DCMAKE_INSTALL_PREFIX=~/opt/GravitySpy-py27 -DCMAKE_BUILD_TYPE=Release
make
make install

cd ..

# Run the following export and add them in your ~/.bashrc file
export CPATH=$CPATH:~/opt/GravitySpy-py27/include
export LIBRARY_PATH=$LIBRARY_PATH:~/opt/GravitySpy-py27/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/opt/GravitySpy-py27/lib

python setup.py build
python setup.py install --prefix=~/opt/GravitySpy-py27/

wget http://www.lsc-group.phys.uwm.edu/daswg/download/software/source/nds2-client-0.15.3.tar.gz
tar -xzf nds2-client-0.15.3.tar.gz
mkdir nds2-client-0.15.3-build
cd nds2-client-0.15.3-build
cmake3 ../nds2-client-0.15.3 -DCMAKE_INSTALL_PREFIX=~/opt/GravitySpy-py27/ -DENABLE_SWIG_JAVA=false -DENABLE_SWIG_MATLAB=false
make
make install
